import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:news_app_c15_mon_offline/core/colors_manager.dart';
import 'package:news_app_c15_mon_offline/features/articles/article_item.dart';
import 'package:news_app_c15_mon_offline/models/article.dart' show Article;
import 'package:news_app_c15_mon_offline/models/category_model.dart';
import 'package:news_app_c15_mon_offline/models/source.dart';

class SourcesView extends StatelessWidget {
  SourcesView({super.key, required this.category});

  CategoryModel category;
  List<Source> sources = [
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
    Source(
      id: "1",
      name: "BBC",
      description: "description",
      url: "url",
      category: "Category",
      language: "En",
      country: "EG",
    ),
  ];
  List<Article> articles = [
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
    Article(
      source: Source(
        id: "id",
        name: "name",
        description: "description",
        url: "url",
        category: "category",
        language: "language",
        country: "country",
      ),
      author: "author",
      title: "title",
      description: "description",
      url: "url",
      urlToImage: "urlToImage",
      publishedAt: "publishedAt",
      content: "content",
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        children: [
          DefaultTabController(
            length: sources.length,
            child: TabBar(
              tabAlignment: TabAlignment.start,
              isScrollable: true,
              indicatorColor: ColorsManager.white,
              dividerColor: Colors.transparent,
              unselectedLabelStyle: GoogleFonts.inter(
                color: Colors.white,
                fontWeight: FontWeight.w500,
                fontSize: 14,
              ),
              labelStyle: GoogleFonts.inter(
                color: Colors.white,
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
              tabs: sources.map((source) => Tab(text: source.name)).toList(),
            ),
          ),
          Expanded(
            child: ListView.separated(
              separatorBuilder: (context, index)=>SizedBox(height: 10.h,),
              itemBuilder: (context, index)=> ArticleItem(article: articles[index]),
              itemCount: articles.length,
            ),
          ),
        ],
      ),
    );
  }
}
